Repository prancer-io/cloud-validation-framework, pull requests merged in 2022-01, with the labels that each got.

#423 Exclusion fixes when complianceId or masterTestID is given.
  setup.py
  src/processor/__init__.py
  src/processor/comparison/interpreter.py
  src/processor/connector/git_connector/git_functions.py
  src/processor/connector/snapshot_azure.py
  src/processor/connector/validation.py
  tests/processor/connector/test_snapshot_azure.py
Labels: bug, enhancement

#428 Azure crawler
  realm/azureApiVersions.json
  src/processor/connector/special_crawler/azure_crawler.py
Labels: enhancement

#425 Exclusion fixes to support masterTestID and complianceID
  docs/docs/cli_run.md
  realm/azureApiVersions.json
  setup.py
  src/processor/__init__.py
  src/processor/comparison/interpreter.py
  src/processor/connector/git_connector/git_functions.py
  src/processor/connector/snapshot_azure.py
  src/processor/connector/special_crawler/azure_crawler.py
  src/processor/connector/validation.py
  src/processor/helper/utils/cli_validator.py
  tests/processor/connector/test_snapshot_azure.py
Labels: bug, enhancement

#436 Fixed missing `type` field issue in generate snapshot after crawler A…
  setup.py
  src/processor/__init__.py
  src/processor/connector/snapshot_aws.py
Labels: bug

#437 Development
  docs/docs/api/collection.md
  setup.py
  src/processor/__init__.py
  src/processor/connector/snapshot_aws.py
Labels: bug

#448 Added config for remote run
  setup.py
  src/processor/__init__.py
  src/processor/helper/config/remote_utils.py
  src/processor/helper/utils/cli_validator.py
Labels: enhancement

#451 Added enhancements for remote run for config.ini and binaries.
  setup.py
  src/processor/__init__.py
  src/processor/helper/config/remote_utils.py
  src/processor/helper/utils/cli_validator.py
Labels: enhancement

#452 Remote fixes for collection configuration
  setup.py
  src/processor/__init__.py
  src/processor/helper/utils/compliance_utils.py
Labels: bug

#455 Fixes to master for crawler and remote run with collection configuration
  setup.py
  src/processor/__init__.py
  src/processor/connector/snapshot_azure.py
  src/processor/helper/utils/compliance_utils.py
Labels: bug

#447 updated documentation
  docs/docs/access.md
  docs/docs/cli_run.md
  docs/docs/configuration/basics.md
  docs/docs/configuration/config.md
  docs/docs/configuration/logging.md
  docs/docs/configuration/secrets.md
  docs/docs/connectors/aws.md
  docs/docs/connectors/azure.md
  docs/docs/connectors/connector-definition.md
  docs/docs/connectors/git.md
  docs/docs/connectors/google.md
  docs/docs/connectors/kubernetes.md
  docs/docs/index.md
  docs/docs/installation.md
  docs/docs/snapshots/google.md
  docs/docs/terminology.md
  docs/docs/tutorials/cicd/codebuild/01-basic-setup.md
  docs/docs/tutorials/cicd/docker/01-build-a-docker-image-and-use.md
  docs/docs/tutorials/cicd/jenkins/01-basic-setup.md
  docs/docs/tutorials/cicd/travis/01-basic-setup.md
  docs/docs/tutorials/connectors/aws/01-security-group.md
  docs/docs/tutorials/connectors/aws/02-testing-values-in-cloudformation-templates.md
  docs/docs/tutorials/connectors/azure/01-security-group.md
  docs/docs/tutorials/connectors/azure/02-testing-values-in-an-arm-templates.md
  docs/docs/workflow.md
Labels: enhancement

#456 Remote fixes typo error
  setup.py
Labels: bug

#457 Master PR for typo and doc fixes.
  docs/docs/access.md
  docs/docs/cli_run.md
  docs/docs/configuration/basics.md
  docs/docs/configuration/config.md
  docs/docs/configuration/logging.md
  docs/docs/configuration/secrets.md
  docs/docs/connectors/aws.md
  docs/docs/connectors/azure.md
  docs/docs/connectors/connector-definition.md
  docs/docs/connectors/git.md
  docs/docs/connectors/google.md
  docs/docs/connectors/kubernetes.md
  docs/docs/index.md
  docs/docs/installation.md
  docs/docs/snapshots/google.md
  docs/docs/terminology.md
  docs/docs/tutorials/cicd/codebuild/01-basic-setup.md
  docs/docs/tutorials/cicd/docker/01-build-a-docker-image-and-use.md
  docs/docs/tutorials/cicd/jenkins/01-basic-setup.md
  docs/docs/tutorials/cicd/travis/01-basic-setup.md
  docs/docs/tutorials/connectors/aws/01-security-group.md
  docs/docs/tutorials/connectors/aws/02-testing-values-in-cloudformation-templates.md
  docs/docs/tutorials/connectors/azure/01-security-group.md
  docs/docs/tutorials/connectors/azure/02-testing-values-in-an-arm-templates.md
  docs/docs/workflow.md
  setup.py
Labels: bug, enhancement
